# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/test/seven_seg_rev/seven_seg_rev.cache/wt [current_project]
set_property parent.project_path D:/test/seven_seg_rev/seven_seg_rev.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/test/seven_seg_rev/seven_seg_rev.srcs/sources_1/new/sev_seg_rev.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/test/seven_seg_rev/seven_seg_rev.srcs/constrs_1/new/sev_seg.xdc
set_property used_in_implementation false [get_files D:/test/seven_seg_rev/seven_seg_rev.srcs/constrs_1/new/sev_seg.xdc]


synth_design -top Seven_segment_LED_Display_Controller -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Seven_segment_LED_Display_Controller.dcp

catch { report_utilization -file Seven_segment_LED_Display_Controller_utilization_synth.rpt -pb Seven_segment_LED_Display_Controller_utilization_synth.pb }
